---
title: "Bent Fall 2001"
author: "R. G. Cronce"
date: "12/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bent Brain Ticklers, Fall 2001

## Problem 1

    During the night, snow began to
    fall at a constant rate. Sometime
    later, the highway crew began
    removing snow from the roads with
    their one plow. The rate of snow
    removal (by volume) was constant,
    and the plow moved two miles in the
    first hour and one mile in the second
    hour. How long had it been snowing
    before the crew started?
    
    -- John R. Osborn, IN Alpha'50

TODO

## Problem 2

    George, John, Arthur, and David
    are married, not necessarily respectively,
    to Christine, Eve, Prudence,
    and Rose. They remember that at a
    party years ago various predictions
    had been made. George had said that
    John would not marry Christine.
    John had said that Arthur would
    marry Prudence. Arthur had
    predicted that whomever David
    married, she would not be Eve.
    David, who at that time was more
    interested in sports than matrimony,
    had predicted that the Cowboys
    would win the next Super Bowl. The
    only one to predict correctly was the
    man who married Prudence. Who
    married whom?
    
    -- Adapted from Brain Puzzler's
    Delight by E.R. Emmet

TODO

## Problem 3

    With different letters being
    different digits, the same letter being
    the same digit throughout, and base
    10, solve:
    ADAM+AND+EVE+ON+A=RAFT
    with ADAM and EVE being as close
    as possible.
    
    -- Mathematical Puzzles for Beginners
    & Enthusiasts
    by Geoffrey Mott-Smith

TODO

## Problem 4

    Uncle George (who was younger
    than 100 years old when he received
    this) found this old message that had
    been buried in his inbox:
    
    Sept. 1973
    Dear George,
    When I was last home you were
    wondering whatever became of Pongo
    Pongleton, who used to go swimming
    with you in 1947. Well, I bumped into
    him in Sweatipore last week. He told
    me he moved up here a couple of years
    ago with his wife and two children to
    study the sex life of the wombat or
    some such prurient nonsense. By an
    odd chance the present ages of his
    children (in whole years) multiply to
    your present age. The girl is a
    bookworm, but the boy is mad about
    guns. He has just broken the largest
    window in the house with his dad's airrifle.
    I recall you doing just the same
    when you were exactly his age. It's a
    small world.
    Yours ever,
    Henry
    
    George could remember nothing
    at all about the window incident
    referred to in the letter. But, using
    only Henry's letter and his own date
    of birth, he deduced the exact year in
    which it must have occurred. What
    was George's precise date of birth
    (year, month, and day)?
    
    -- Martin Hollis

TODO

## Problem 5

    Drawing the five diagonals in a
    convex pentagon results in a
    five-pointed star. At each point of the
    star, between the sides of the
    star and the sides of the pentagon,
    are two angles (i.e., angles
    exterior to the star and bounded by
    the pentagon). What is the sum, in
    degrees, of the measures of these 10
    angles?
    
    -- Technology Review

TODO

## Bonus

    A student starts with the
    familiar series 1 + 1/2 + 1/4 +
    1/8 + . . . . He then takes the average
    of each adjacent pair of terms and
    inserts it between the terms to
    obtain the new series 1 + 3/4 + 1/2 +
    3/8 + 1/4 + . . . . He divides this by
    two, because there are now twice as
    many terms as before. He repeats
    the process indefinitely. What exact
    limit will the series approach?
    
    -- Litton Industries
    "Problematical Recreations"

TODO

## Double Bonus

    Decipher the
    following phrases (where each
    capital letter is the first letter of a
    word, e.g., 10 = Decimal Digits):
    1 = W. on a U.
    2 = S. to an I.
    3 = B. M. (S. H. T. R.)
    4 = Q. in a G.
    5 = D. in a Z. C.
    6 = S. on a C.
    7 = W. of the A. W.
    8 = S. on a S. S.
    9 = P. in the S. S.
    10 = D. D.
    11 = P. on a F. T.
    12 = S. of the Z.
    13 = S. on the A. F.
    18 = H. on a G. C.
    24 = H. in a D.
    26 = L. of the A.
    29 = D. in F. in a L. Y.
    32 = D. F. at which W. F.
    40 = D. and N. of the G. F.
    54 = C. in a D. (with the J.)
    57 = H. V.
    64 = S. on a C.
    88 = K. on a P.
    90 = D. in a R. A.
    200 = D. for P. G. in M.
    1000 = W. that a P. is W.
    1001 = A. N.
    
    -- Adapted from The Crucible

TODO

